# Generated by Django 2.1.5 on 2019-05-16 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='joined',
            field=models.ManyToManyField(related_name='joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
