# Generated by Django 2.1.5 on 2019-05-16 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20190516_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='joined',
            field=models.ManyToManyField(blank=True, related_name='joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
